# Generated by Django 5.0.1 on 2024-02-03 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_brand_alter_item_brand_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), default=list, size=None),
        ),
    ]
